"""
Django settings for djecommerce project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y(g5diq5igy!2x)8e9k#w(9j5ah%^9#sy1+^z@xdzx*seg4#e('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# #django-allauth 
# # Make sure to add these required apps
#     'django.contrib.sites',
# # Django-allauth apps
#     'allauth',
#     'allauth.account',
#     'allauth.socialaccount',
# #app
    "core",
    'crispy_forms',
    "django_countries",
    'dbbackup',  # django-dbbackup
    "users",
    "widget_tweaks",
    "django.contrib.humanize",
    "django_filters",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobsearchappp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobsearchappp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': "core",
        "USER": "postgres",
        "PASSWORD":"1234",
        "PORT": "5432",
        "HOST": "localhost",

    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

LANGUAGES = [
    ('en', 'English'),
    #('tr', 'Turkish'),

]   

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#crispy forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#AUTH_USER_MODEL = "auth.User"
AUTH_USER_MODEL = "users.User"
AUTHENTICATION_BACKENDS = ["users.backends.EmailBackend"]


###################### Stripe Deneme ######################
#STRIPE_PUBLIC_KEY = 'pk_test_51LRHgKCuSbiK1P40oO79xktlCEnhjOH6JblCOdB0YoPyXZY5Rm5vIk1fhIhof8RcPLN2bcHLk26RMHlrzhH3APSK00EOBwfDdu'
STRIPE_PUBLIC_KEY = "pk_test_51MXQmmDRFtFaIQsZS27L1vXrHDfueDDhz5KnMiIuXUxznKMKWFqzIHTW2ys2Ba0F99KliekNT3y2fCrwkl5aHeF6006KiBfYzd"
#STRIPE_SECRET_KEY = 'sk_test_51LRHgKCuSbiK1P402FP3hdEEjcMSGLOsviQBTNAjbiyLFeMekljigAHuW07LNj2FVBrPfyUm9RhxYgrmTJCYLWDc00rD9ogCeg'
STRIPE_SECRET_KEY = "sk_test_51MXQmmDRFtFaIQsZT0H4hEteI7pXQOIWl03Pn77SuqdIrAYWiuNuPQMe2EkVXJ1pM26aMTPm6enrSXDKVVx3UUvV00teUOzACv"
STRIPE_WEBHOOK_SECRET = ""
STRIPE_ENDPOINT_SECRET = 'whsec_0c10507e18d883ea2880896757ef56e3e1a75f5d338b08cc68c9fff990adf82f'
###################### Stripe Deneme ######################

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': 'backups/dir/'}

ACCOUNT_SID = "AC595d6d593eca3845d9da7bad6631fc24"
AUTH_TOKEN = "a3e2375f85bd1ba4a3da2728ed4e2342"
